// Small local WebGL renderer. World coordinates retain Quake's Z-up convention.
class SketchRenderer {
 // BSP polygons can start with several collinear vertices. Newell's method
 // uses the entire boundary instead of choosing an arbitrary first triangle.
 static polygonNormal(p){const n=[0,0,0];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];n[0]+=(a[1]-b[1])*(a[2]+b[2]);n[1]+=(a[2]-b[2])*(a[0]+b[0]);n[2]+=(a[0]-b[0])*(a[1]+b[1])}const length=Math.hypot(...n);return Number.isFinite(length)&&length>1e-8?n.map(v=>v/length):null}
 constructor(canvas){
  this.canvas=canvas;const gl=this.gl=canvas.getContext('webgl',{antialias:true});if(!gl)throw Error('WebGL недоступен в этом браузере');
  const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
  const program=this.program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uVP;uniform mat4 uModel;varying float light;varying float distance;void main(){vec4 world=uModel*vec4(aPosition,1.0);gl_Position=uVP*world;vec3 n=normalize(mat3(uModel)*aNormal);light=.38+.62*abs(dot(n,normalize(vec3(.3,.5,.85))));distance=gl_Position.w;}`));
  gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform vec3 uColor;uniform float uEdge;varying float light;varying float distance;void main(){vec3 color=uColor*light;float fog=clamp(distance/3200.,0.,.78);gl_FragColor=vec4(mix(color,vec3(.045,.065,.085),fog),1.0);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
  this.position=gl.getAttribLocation(program,'aPosition');this.normal=gl.getAttribLocation(program,'aNormal');this.vp=gl.getUniformLocation(program,'uVP');this.model=gl.getUniformLocation(program,'uModel');this.color=gl.getUniformLocation(program,'uColor');this.meshes=new Map();this.box=this.makeBox();gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);this.identity=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
 }
 mesh(polygons){const solid=[],edges=[];for(const p of polygons){if(p.length<3)continue;const a=p[0],n=SketchRenderer.polygonNormal(p);if(!n)continue;const add=(target,q)=>target.push(...q,...n);for(let i=1;i<p.length-1;i++)for(const q of [a,p[i],p[i+1]])add(solid,q);for(let i=0;i<p.length;i++){add(edges,p[i]);add(edges,p[(i+1)%p.length])}}const buffer=data=>{const b=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,b);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(data),this.gl.STATIC_DRAW);return{buffer:b,count:data.length/6}};return{solid:buffer(solid),edges:buffer(edges)}}
 makeBox(){const p=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];return this.mesh([[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]].map(face=>face.map(i=>p[i])))}
 setMap(data){for(const mesh of this.meshes.values()){this.gl.deleteBuffer(mesh.solid.buffer);this.gl.deleteBuffer(mesh.edges.buffer)}this.meshes.clear();const groups=new Map();data.polygons.forEach((p,i)=>{const model=data.models[i]||0;if(!groups.has(model))groups.set(model,[]);groups.get(model).push(p)});for(const [id,polygons]of groups)this.meshes.set(id,this.mesh(polygons));this.polygonCount=data.polygons.length}
 matrix(origin=[0,0,0],angles=[0,0,0],scale=[1,1,1]){const yaw=angles[1]*Math.PI/180,c=Math.cos(yaw),s=Math.sin(yaw);return new Float32Array([c*scale[0],s*scale[0],0,0,-s*scale[1],c*scale[1],0,0,0,0,scale[2],0,...origin,1])}
 camera(eye,angles,fov,aspect){const pitch=angles[0]*Math.PI/180,yaw=angles[1]*Math.PI/180,roll=angles[2]*Math.PI/180;const forward=[Math.cos(pitch)*Math.cos(yaw),Math.cos(pitch)*Math.sin(yaw),-Math.sin(pitch)],r=[Math.sin(yaw),-Math.cos(yaw),0],up=[Math.sin(pitch)*Math.cos(yaw),Math.sin(pitch)*Math.sin(yaw),Math.cos(pitch)];const right=r.map((x,i)=>x*Math.cos(roll)+up[i]*Math.sin(roll)),top=up.map((x,i)=>x*Math.cos(roll)-r[i]*Math.sin(roll)),dot=v=>v.reduce((n,x,i)=>n+x*eye[i],0);const view=[right[0],top[0],-forward[0],0,right[1],top[1],-forward[1],0,right[2],top[2],-forward[2],0,-dot(right),-dot(top),dot(forward),1];const fx=1/Math.tan(Math.max(30,Math.min(130,fov))*Math.PI/360),near=2,far=12000,projection=[fx,0,0,0,0,fx*aspect,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0],result=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)result[c*4+r]+=projection[k*4+r]*view[c*4+k];return result}
 drawMesh(mesh,matrix,color){const gl=this.gl;gl.uniformMatrix4fv(this.model,false,matrix);const draw=(part,mode,col)=>{gl.bindBuffer(gl.ARRAY_BUFFER,part.buffer);gl.enableVertexAttribArray(this.position);gl.enableVertexAttribArray(this.normal);gl.vertexAttribPointer(this.position,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(this.normal,3,gl.FLOAT,false,24,12);gl.uniform3fv(this.color,col);gl.drawArrays(mode,0,part.count)};gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);draw(mesh.solid,gl.TRIANGLES,color);gl.disable(gl.POLYGON_OFFSET_FILL);draw(mesh.edges,gl.LINES,color.map(v=>Math.min(1,v*1.3+.06)))}
 render(frame,next,fraction){if(!frame)return;const gl=this.gl,w=Math.max(1,this.canvas.clientWidth),h=Math.max(1,this.canvas.clientHeight),dpr=Math.min(devicePixelRatio||1,1.5);if(this.canvas.width!==Math.round(w*dpr)||this.canvas.height!==Math.round(h*dpr)){this.canvas.width=Math.round(w*dpr);this.canvas.height=Math.round(h*dpr)}gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(.045,.065,.085,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);
  const valid=next&&next.map===frame.map&&next.frame>frame.frame&&Math.hypot(...next.self.map((v,i)=>v-frame.self[i]))<512,t=valid?fraction:0,lerp=(a,b)=>a.map((v,i)=>v+((b||a)[i]-v)*t),angleLerp=(a,b)=>a.map((v,i)=>v+((((b||a)[i]-v+540)%360)-180)*t);const eye=lerp(frame.eye,next?.eye),angles=angleLerp(frame.angles,next?.angles);gl.uniformMatrix4fv(this.vp,false,this.camera(eye,angles,frame.fov||90,w/h));
  const world=this.meshes.get(0);if(world)this.drawMesh(world,this.identity,[.36,.43,.47]);const later=new Map((next?.entities||[]).map(e=>[e.id,e]));
  for(const entity of frame.entities||[]){const other=later.get(entity.id),origin=lerp(entity.origin,other?.origin),model=entity.model||'';if(model.startsWith('*')){const mesh=this.meshes.get(Number(model.slice(1)));if(mesh)this.drawMesh(mesh,this.matrix(origin,entity.angles),[.42,.52,.55]);continue}let color,size,z=0;if(model.includes('monsters')||model.includes('players')||model===''){color=[.85,.31,.22];size=[14,14,28];z=8}else if(/weapons|items|objects/.test(model)){color=[.36,.78,.52];size=[9,9,10];z=8}else{color=[.98,.69,.24];size=[4,4,4]};this.drawMesh(this.box,this.matrix([origin[0],origin[1],origin[2]+z],entity.angles,size),color)}
 }
}
window.SketchRenderer=SketchRenderer;
