let demoItems=[],demoRenderer=null,demoGeneration=0,loadedDemoFrames=[],meshCache=new Map(),demoResponseCache=new Map();
function demoFrameInterval(){if($('viewMode').value!=='demo')return 100;const a=points[index],b=points[index+1];return b&&a&&b.frame>a.frame?(b.frame-a.frame)*100:100}
function demoMode(){return $('viewMode').value==='demo'}
function switchDemoDOM(){const enabled=demoMode();$('demoCanvas').hidden=!enabled;$('demoHUD').hidden=!enabled;$('demoSelect').hidden=!enabled;$('demoCanvas').parentElement.classList.toggle('demo-mode',enabled);$('fit').disabled=enabled;for(const id of ['heightFilter','height','tolerance','friend'])$(id).disabled=enabled}
async function conditionalJSON(url,cache){const cached=cache.get(url),response=await fetch(url,{headers:cached?{'If-None-Match':cached.etag}:{}});if(response.status===304&&cached)return cached.data;if(!response.ok)throw Error(await response.text());const data=await response.json();cache.set(url,{data,etag:response.headers.get('ETag')});return data}
const traceSelectRun=selectRun,traceSelectMap=selectMap,traceDraw=draw;
selectRun=async function(run){++demoGeneration;demoItems=[];loadedDemoFrames=[];const previousMode=$('viewMode').value;$('viewMode').value='map';switchDemoDOM();await traceSelectRun(run);if(selected!==run.id)return;const generation=demoGeneration;try{const data=await get('/api/demos?id='+encodeURIComponent(run.id));if(generation!==demoGeneration||selected!==run.id)return;demoItems=data.items;$('demoSelect').replaceChildren(...demoItems.map(item=>new Option(`${item.name}${item.error?' · ошибка':''}`,item.name)));if(previousMode==='demo'||new URLSearchParams(location.search).get('view')==='demo'){$('viewMode').value='demo';await selectMap()}}catch(error){if(generation===demoGeneration)message(error.message)}};
selectMap=async function(){if(!demoMode()){++demoGeneration;switchDemoDOM();return traceSelectMap()}const generation=++demoGeneration;hideTooltip();stop();points=[];index=0;switchDemoDOM();$('heading').textContent=$('mapSelect').value;message('Читаем сетевые кадры демо и 3D-геометрию BSP…');draw();const map=$('mapSelect').value;
 try{if(!demoItems.length)throw Error('Для этого прогона нет .dm2. Выберите новый прогон с записью демо.');let item=demoItems.find(item=>item.name===$('demoSelect').value&&item.maps?.includes(map))||demoItems.find(item=>item.maps?.includes(map));if(!item)throw Error('В демках этого прогона нет выбранной карты.');if(item.error)throw Error(item.error);$('demoSelect').value=item.name;const [demo,mesh]=await Promise.all([conditionalJSON('/api/demo?id='+encodeURIComponent(selected)+'&name='+encodeURIComponent(item.name),demoResponseCache),conditionalJSON('/api/map.mesh?name='+encodeURIComponent(map),meshCache)]);if(generation!==demoGeneration||!demoMode())return;loadedDemoFrames=demo.frames;points=loadedDemoFrames.filter(frame=>frame.map===map);if(!points.length)throw Error('В демке пока нет полных кадров выбранной карты.');if(!demoRenderer)demoRenderer=new SketchRenderer($('demoCanvas'));demoRenderer.setMap(mesh);index=0;playbackPosition=0;$('timeline').max=points.length-1;$('timeline').value=0;message(`${item.name} · ${points.length} кадров · ${mesh.polygons.length} граней BSP · без текстур, модели заменены фигурами${demo.complete?'':' · запись ещё идёт или не завершена'}`);draw()}catch(error){if(generation===demoGeneration){message(error.message);$('demoHUD').textContent=error.message}}};
draw=function(){if(!demoMode())return traceDraw();switchDemoDOM();updatePlayState();const frame=points[index];if(!frame||!demoRenderer){$('frame').textContent='—';$('demoHUD').replaceChildren();return}const next=points[index+1],fraction=playing?playbackPosition-index:0;demoRenderer.render(frame,next,fraction);$('frame').textContent=`${frame.frame} / ${points.length}`;$('coords').textContent=frame.self.map(fmt).join(' · ');$('health').textContent=frame.health;$('distance').textContent='—';$('details').textContent=`Демо от лица бота · ${frame.entities.length} объектов · ${frame.weapon.split('/').slice(-2,-1)[0]||'оружие'} · броня ${frame.armor} · патроны ${frame.ammo}`;const stats=document.createElement('span'),weapon=document.createElement('span');stats.textContent=`HP ${frame.health} · Броня ${frame.armor} · Патроны ${frame.ammo}`;stats.style.color=healthColor(frame.health);weapon.textContent=`${frame.weapon.split('/').slice(-2,-1)[0]||'Оружие'} · кадр ${frame.frame}`;$('demoHUD').replaceChildren(stats,weapon)};
$('viewMode').onchange=()=>{selectMap()};$('demoSelect').onchange=()=>selectMap();$('mapSelect').onchange=()=>selectMap();new ResizeObserver(()=>{if(demoMode())draw()}).observe($('demoCanvas'));
// Start after both playback modes have installed their handlers.
refresh();
