[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$RuntimeRoot,
    [string]$AssetsRoot='F:/src/quake2/assets/baseq2'
)
$ErrorActionPreference='Stop'
$repo=Split-Path $PSScriptRoot -Parent
$boundary=[IO.Path]::GetFullPath((Join-Path $repo 'workspace/artifacts')).TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar
$runtime=(Resolve-Path -LiteralPath $RuntimeRoot).Path.TrimEnd('\','/')
if(!$runtime.StartsWith($boundary,[StringComparison]::OrdinalIgnoreCase)){throw 'PAK cleanup is limited to generated artifact runtimes'}
for($directory=[IO.DirectoryInfo]::new($runtime);$directory -and $directory.FullName.StartsWith($boundary.TrimEnd('\'),[StringComparison]::OrdinalIgnoreCase);$directory=$directory.Parent){
    if($directory.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'PAK cleanup refuses junction ancestors'}
}
if((Get-Item -LiteralPath $runtime).Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Runtime root must not be a junction'}
$marker=Join-Path $runtime '.q2go-prepared-runtime'
if(!(Test-Path -LiteralPath $marker) -or (Get-Content -LiteralPath $marker -Raw).Trim() -ne 'Go UDP test runtime; generated by scripts/prepare_runtime.ps1'){throw 'Owned runtime marker required for PAK cleanup'}
$baseq2=Join-Path $runtime 'baseq2'
if((Get-Item -LiteralPath $baseq2).Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Runtime baseq2 must not be a junction'}
$active=@(Get-CimInstance Win32_Process|Where-Object {$_.ExecutablePath -and $_.ExecutablePath.StartsWith($runtime+'\',[StringComparison]::OrdinalIgnoreCase)})
if($active.Count){throw 'Cannot clean resources of a running runtime'}
$removed=@()
foreach($name in @('pak0.pak','pak1.pak','pak2.pak')){
    $target=Join-Path $baseq2 $name;$source=Join-Path $AssetsRoot $name
    if(!(Test-Path -LiteralPath $target)){continue}
    if(!(Test-Path -LiteralPath $source)){throw "Canonical PAK missing: $source"}
    if((Get-Item -LiteralPath $target).Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'PAK cleanup refuses symbolic links'}
    $digest=(Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash
    if((Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash -ne $digest){throw "Runtime PAK differs from canonical asset: $target"}
    $removed+=@{path=$target;sha256=$digest;bytes=(Get-Item -LiteralPath $target).Length;source=$source}
}
# All sources and targets are verified before removing any directory entry.
foreach($record in $removed){Remove-Item -LiteralPath $record.path}
@{version='completed_runtime_pak_cleanup_v1';runtime=$runtime;removed=$removed;scope='Server stopped; duplicate PAK entries only. Shared canonical resources, engine, DLL, logs, datasets and configuration retained.'}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $runtime 'pak-cleanup.json') -Encoding utf8NoBOM
