[CmdletBinding()]
param(
    [string]$AssetsRoot = 'F:\src\quake2\q2coopbot-runtime-vanilla\baseq2',
    [string]$ServerExe = 'F:\src\quake2\yquake2\build\codex-speed-test\release\q2ded.exe',
    [string]$GameDll = 'F:\src\quake2\yquake2\build\codex-speed-test\release\baseq2\game.dll',
    [string]$RuntimeRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) 'workspace\runtime\q2go')
)

$ErrorActionPreference = 'Stop'
foreach ($path in @($AssetsRoot, $ServerExe, $GameDll)) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Required input is missing: $path" }
}
$marker = Join-Path $RuntimeRoot '.q2go-prepared-runtime'
if ((Test-Path -LiteralPath $RuntimeRoot) -and -not (Test-Path -LiteralPath $marker)) {
    throw "Target already exists and was not created by this script: $RuntimeRoot"
}
$baseq2 = Join-Path $RuntimeRoot 'baseq2'
$maps = Join-Path $baseq2 'maps'
New-Item -ItemType Directory -Path $maps -Force | Out-Null
foreach ($name in @('pak0.pak', 'pak1.pak', 'pak2.pak')) {
    $source = Join-Path $AssetsRoot $name
    if (-not (Test-Path -LiteralPath $source)) { continue }
    $target = Join-Path $baseq2 $name
    if (Test-Path -LiteralPath $target) { continue }
    if ([IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $source).Path) -eq [IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $RuntimeRoot).Path)) {
        New-Item -ItemType HardLink -Path $target -Target $source | Out-Null
    } else {
        Copy-Item -LiteralPath $source -Destination $target
    }
}
if (-not (Test-Path -LiteralPath (Join-Path $baseq2 'pak0.pak'))) { throw 'pak0.pak is required.' }
$sourceMaps = Join-Path $AssetsRoot 'maps'
if (Test-Path -LiteralPath $sourceMaps) {
    Get-ChildItem -LiteralPath $sourceMaps -Filter '*.aas' -File | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $maps $_.Name) -Force
    }
}
Copy-Item -LiteralPath $ServerExe -Destination (Join-Path $RuntimeRoot 'q2ded.exe') -Force
Copy-Item -LiteralPath $GameDll -Destination (Join-Path $baseq2 'game.dll') -Force
Set-Content -LiteralPath $marker -Value 'Go UDP test runtime; generated by scripts/prepare_runtime.ps1' -Encoding UTF8
Write-Output "Prepared $RuntimeRoot"
