[CmdletBinding()]
param(
    [string]$AssetsRoot = 'F:\src\quake2\assets\baseq2',
    [string]$AASRoot = '',
    [string]$ServerExe = 'F:\src\quake2\yquake2\build\codex-speed-test\release\q2ded.exe',
    [string]$GameDll = 'F:\src\quake2\yquake2\build\codex-speed-test\release\baseq2\game.dll',
    [string]$RuntimeRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) 'workspace\runtime\q2go')
)

$ErrorActionPreference = 'Stop'
# Replace the directory entry, not the contents of a potentially shared hard link.
# Live sessions may still be using the previous AAS through another path.
function Install-RuntimeAAS([string]$Source, [string]$Target) {
    $temporary = $Target + '.' + [guid]::NewGuid().ToString('N') + '.tmp'
    try {
        Copy-Item -LiteralPath $Source -Destination $temporary
        if (Test-Path -LiteralPath $Target) {
            [IO.File]::Replace($temporary, $Target, [NullString]::Value)
        } else {
            [IO.File]::Move($temporary, $Target)
        }
    } finally {
        if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary }
    }
}
foreach ($path in @($AssetsRoot, $ServerExe, $GameDll)) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Required input is missing: $path" }
}
if ($AASRoot -and -not (Test-Path -LiteralPath $AASRoot -PathType Container)) {
    throw "AAS directory is missing: $AASRoot"
}
$additionalAAS = @()
if ($AASRoot) {
    $additionalAAS = @(Get-ChildItem -LiteralPath $AASRoot -Filter '*.aas' -File)
    if ($additionalAAS.Count -eq 0) { throw "No AAS files found in: $AASRoot" }
    foreach ($aas in $additionalAAS) {
        $data = [IO.File]::ReadAllBytes($aas.FullName)
        if ($data.Length -lt 120 -or [Text.Encoding]::ASCII.GetString($data, 0, 4) -ne 'EAAS') {
            throw "Invalid AAS header: $($aas.FullName)"
        }
        $version = [BitConverter]::ToInt32($data, 4)
        if ($version -notin @(2, 3, 4, 5)) { throw "Unsupported AAS version $version`: $($aas.FullName)" }
        $headerSize = if ($version -ge 4) { 124 } else { 120 }
        if ($data.Length -lt $headerSize) { throw "Truncated AAS header: $($aas.FullName)" }
        $header = [byte[]]$data[0..($headerSize - 1)]
        if ($version -eq 5) {
            for ($i = 8; $i -lt $headerSize; $i++) {
                $header[$i] = $header[$i] -bxor [byte]((($i - 8) * 119) -band 255)
            }
        }
        $reachDirectory = $headerSize - 14 * 8 + 9 * 8
        $reachOffset = [BitConverter]::ToInt32($header, $reachDirectory)
        $reachLength = [BitConverter]::ToInt32($header, $reachDirectory + 4)
        if (
            $reachLength -le 0 -or $reachLength % 44 -ne 0 -or $reachOffset -lt $headerSize -or
            $reachOffset -gt $data.Length -or $reachLength -gt $data.Length - $reachOffset) {
            throw "AAS has no reachability data: $($aas.FullName)"
        }
    }
}
$marker = Join-Path $RuntimeRoot '.q2go-prepared-runtime'
if ((Test-Path -LiteralPath $RuntimeRoot) -and -not (Test-Path -LiteralPath $marker)) {
    throw "Target already exists and was not created by this script: $RuntimeRoot"
}
$baseq2 = Join-Path $RuntimeRoot 'baseq2'
$maps = Join-Path $baseq2 'maps'
New-Item -ItemType Directory -Path $maps -Force | Out-Null
foreach ($name in @('pak0.pak', 'pak1.pak', 'pak2.pak')) {
    $source = Join-Path $AssetsRoot $name
    if (-not (Test-Path -LiteralPath $source)) { continue }
    $target = Join-Path $baseq2 $name
    if (Test-Path -LiteralPath $target) { continue }
    if ([IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $source).Path) -eq [IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $RuntimeRoot).Path)) {
        New-Item -ItemType HardLink -Path $target -Target $source | Out-Null
    } else {
        Copy-Item -LiteralPath $source -Destination $target
    }
}
if (-not (Test-Path -LiteralPath (Join-Path $baseq2 'pak0.pak'))) { throw 'pak0.pak is required.' }
$sourceMaps = Join-Path $AssetsRoot 'maps'
if (Test-Path -LiteralPath $sourceMaps) {
    Get-ChildItem -LiteralPath $sourceMaps -Filter '*.aas' -File | ForEach-Object {
        $target = Join-Path $maps $_.Name
        # Asset archives can contain older graphs. Updates must use explicit AASRoot.
        if (-not (Test-Path -LiteralPath $target)) {
            Install-RuntimeAAS $_.FullName $target
        }
    }
}
foreach ($aas in $additionalAAS) {
    Install-RuntimeAAS $aas.FullName (Join-Path $maps $aas.Name)
}
Copy-Item -LiteralPath $ServerExe -Destination (Join-Path $RuntimeRoot 'q2ded.exe') -Force
Copy-Item -LiteralPath $GameDll -Destination (Join-Path $baseq2 'game.dll') -Force
Set-Content -LiteralPath $marker -Value 'Go UDP test runtime; generated by scripts/prepare_runtime.ps1' -Encoding UTF8
Write-Output "Prepared $RuntimeRoot"
