$ErrorActionPreference='Stop'
$repo=Split-Path $PSScriptRoot -Parent
$testRoot=Join-Path $repo ('workspace/artifacts/pak-cleanup-test-'+[guid]::NewGuid().ToString('N'))
$source=Join-Path $testRoot 'canonical';New-Item -ItemType Directory -Path $source|Out-Null
foreach($name in 'pak0.pak','pak1.pak'){[IO.File]::WriteAllText((Join-Path $source $name),"immutable $name")}
function Make-TestRuntime([string]$name){
    $runtime=Join-Path $testRoot $name;$base=Join-Path $runtime 'baseq2'
    New-Item -ItemType Directory -Path $base -Force|Out-Null
    Set-Content (Join-Path $runtime '.q2go-prepared-runtime') 'Go UDP test runtime; generated by scripts/prepare_runtime.ps1'
    foreach($pak in 'pak0.pak','pak1.pak'){Copy-Item -LiteralPath (Join-Path $source $pak) -Destination (Join-Path $base $pak)}
    Set-Content (Join-Path $runtime 'server.log') 'preserve log'
    return $runtime
}
$cleanup=Join-Path $PSScriptRoot 'cleanup_completed_runtime_paks.ps1'
$runtime=Make-TestRuntime 'valid'; & $cleanup -RuntimeRoot $runtime -AssetsRoot $source
if(@(Get-ChildItem (Join-Path $runtime 'baseq2') -Filter '*.pak').Count){throw 'Completed PAKs retained'}
if(!(Test-Path (Join-Path $runtime 'server.log')) -or !(Test-Path (Join-Path $source 'pak0.pak'))){throw 'Canonical or log removed'}
& $cleanup -RuntimeRoot $runtime -AssetsRoot $source
$runtime=Make-TestRuntime 'corrupt';Set-Content (Join-Path $runtime 'baseq2/pak1.pak') 'different'
try{& $cleanup -RuntimeRoot $runtime -AssetsRoot $source;throw 'Expected corruption rejection'}catch{if($_.Exception.Message -notmatch 'differs from canonical'){throw}}
if(!(Test-Path (Join-Path $runtime 'baseq2/pak0.pak'))){throw 'Cleanup was not atomic with respect to verification'}
$runtime=Make-TestRuntime 'unowned';Remove-Item -LiteralPath (Join-Path $runtime '.q2go-prepared-runtime')
try{& $cleanup -RuntimeRoot $runtime -AssetsRoot $source;throw 'Expected marker rejection'}catch{if($_.Exception.Message -notmatch 'Owned runtime marker'){throw}}
try{& $cleanup -RuntimeRoot (Join-Path $repo 'workspace/build') -AssetsRoot $source;throw 'Expected boundary rejection'}catch{if($_.Exception.Message -notmatch 'limited to generated artifact'){throw}}
$real=Make-TestRuntime 'junction-target';$junction=Join-Path $testRoot 'junction'
New-Item -ItemType Junction -Path $junction -Target $real|Out-Null
try{& $cleanup -RuntimeRoot $junction -AssetsRoot $source;throw 'Expected junction rejection'}catch{if($_.Exception.Message -notmatch 'junction'){throw}}
'PASS: verified cleanup, canonical/log preservation, idempotence, corrupt/marker/boundary/junction rejection'
